language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.app/cache

env:
  global:
    - deps="no"
    - SYMFONY_VERSION=""
    - PHP_CS="no"
    - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.* SYMFONY_DEPRECATIONS_HELPER=strict
    - php: 5.6
      env: SYMFONY_VERSION=3.0.* SYMFONY_DEPRECATIONS_HELPER=strict
    - php: 5.6
      env: SYMFONY_VERSION="dev-master as 3.1" SYMFONY_DEPRECATIONS_HELPER=strict
    - php: 5.6
      env: TWIG_VERSION="2.0.x-dev"
  allow_failures:
    - php: hhvm
    - env: SYMFONY_VERSION="dev-master as 3.1"
    - env: TWIG_VERSION="2.0.x-dev"

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" =~ 5.3 ]] && [[ "$COMPOSER_FLAGS" != "--prefer-lowest" ]]; then export PHP_CS="yes"; fi;
  - if [[ "$PHP_CS" == "yes" ]]; then mv $HOME/.app/cache/.php_cs.cache ./.php_cs.cache 2>/dev/null || true; fi;
  - if [[ "$SYMFONY_VERSION" = "" ]] && [[ "$TWIG_VERSION" = "" ]] && [[ "$TRAVIS_PHP_VERSION" =~ 5.[45] ]] && [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then export skip="yes"; fi;
  - if [[ "$skip" != "yes" ]]; then composer selfupdate; fi
  - if [[ "$skip" != "yes" && "$SYMFONY_VERSION" != "" ]]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [[ "$skip" != "yes" && "$TWIG_VERSION" != "" ]]; then composer require "twig/twig:${TWIG_VERSION}" --no-update; fi;
  - if [[ "$skip" != "yes" && "$SYMFONY_VERSION" != "2.8.*" && "$TRAVIS_PHP_VERSION" != 7.0 && "$TRAVIS_PHP_VERSION" != hhvm ]]; then phpenv config-rm xdebug.ini; fi;

install:
  - if [[ "$PHP_CS" == "yes" ]]; then curl http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer; fi;
  - if [[ "$skip" != "yes" ]]; then composer update --prefer-dist --no-interaction $COMPOSER_FLAGS; fi
  - if [[ "$skip" != "yes" && "$SYMFONY_VERSION" == "2.8.*" ]]; then composer require --dev satooshi/php-coveralls:~0.6; fi

script:
  - if [[ "$skip" != "yes" && "$SYMFONY_VERSION" == "2.8.*" ]]; then phpunit --coverage-text --coverage-clover build/logs/clover.xml; else if [[ "$skip" != "yes" ]]; then phpunit; fi; fi
  - if [[ "$skip" = "yes" ]]; then echo "Skipping matrix entry for pull requests"; fi
  - if [[ "$PHP_CS" == "yes" ]]; then php php-cs-fixer --no-interaction --dry-run --diff -v fix; fi;
  - if [[ "$PHP_CS" == "yes" ]]; then mv ./.php_cs.cache $HOME/.app/cache/.php_cs.cache; fi;

after_success: |
    if [[ "$SYMFONY_VERSION" == "2.8.*" ]]; then php vendor/bin/coveralls -v --config .coveralls.yml; fi;
