language: php

sudo: false

env:
  global:
    - deps="no"
    - SYMFONY_VERSION=""

matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 5.6
      env: SYMFONY_VERSION="2.6.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.7.x-dev"
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: 5.6
      env: deps="low"
    - php: 5.6
      env: SYMFONY_VERSION="2.3.x"
    - php: hhvm
    - php: nightly

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi

install:
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; fi
  - if [ "$deps" != "low" ]; then composer install; fi
