build: false
clone_depth: 1
clone_folder: c:\projects\easyadmin-bundle

cache:
    - c:\php -> appveyor.yml
    - .phpunit -> phpunit

init:
    - SET PATH=c:\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET SYMFONY_DEPRECATIONS_HELPER=strict
    - SET PHP=1
    - SET ANSICON=121x90 (121x90)

install:
    - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
    - cd c:\php
    - IF %PHP%==1 appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-5.5.9-nts-Win32-VC11-x86.zip
    - IF %PHP%==1 7z x php-5.5.9-nts-Win32-VC11-x86.zip -y >nul
    - IF %PHP%==1 del /Q *.zip
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - IF %PHP%==1 copy /Y php.ini-development php.ini
    - IF %PHP%==1 echo max_execution_time=1200 >> php.ini
    - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - IF %PHP%==1 echo apc.enable_cli=1 >> php.ini
    - IF %PHP%==1 echo extension=php_intl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
    - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
    - IF %PHP%==1 echo extension=php_pdo_sqlite.dll >> php.ini
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - appveyor DownloadFile https://phar.phpunit.de/phpunit-old.phar
    - copy /Y phpunit-old.phar phpunit.phar
    - cd c:\projects\easyadmin-bundle
    - mkdir %APPDATA%\Composer
    - IF %APPVEYOR_REPO_BRANCH%==master (SET COMPOSER_ROOT_VERSION=dev-master) ELSE (SET COMPOSER_ROOT_VERSION=%APPVEYOR_REPO_BRANCH%.x-dev)
    - composer update --prefer-dist --no-progress --ansi

test_script:
    - cd c:\projects\easyadmin-bundle
    - SET X=0
    - php c:\php\phpunit.phar
    - exit %X%
