build: false
shallow_clone: true
platform: x86
clone_folder: c:\projects\easyadmin-bundle

cache:
    - c:\php -> appveyor.yml

init:
    - SET PATH=c:\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET SYMFONY_DEPRECATIONS_HELPER=strict
    - SET ANSICON=121x90 (121x90)

install:
    - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
    - cd c:\php
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - appveyor DownloadFile https://phar.phpunit.de/phpunit-4.8.15.phar
    - appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-5.3.11-nts-Win32-VC9-x86.zip
    - 7z x php-5.3.11-nts-Win32-VC9-x86.zip -y >nul
    - copy /Y php.ini-development php.ini
    - echo max_execution_time=1200 >> php.ini
    - echo date.timezone="UTC" >> php.ini
    - echo extension_dir=ext >> php.ini
    - echo apc.enable_cli=1 >> php.ini
    - echo extension=php_openssl.dll >> php.ini
    - echo extension=php_intl.dll >> php.ini
    - echo extension=php_mbstring.dll >> php.ini
    - echo extension=php_pdo_sqlite.dll >> php.ini
    - cd c:\projects\easyadmin-bundle
    - composer.phar update %COMPOSER_FLAGS% --prefer-source --no-progress --ansi

test_script:
    - phpunit-4.8.15.phar
