# OS: Linux; Symfony: latest stable; PHP: upcoming (still unreleased) version
name: "Tests - Upcoming PHP version"

on:
    pull_request:
    push:
        branches:
            - '4.x'

env:
    fail-fast: true

permissions:
  contents: read

jobs:
    tests:
        runs-on: 'ubuntu-latest'
        continue-on-error: true
        strategy:
            matrix:
                php-version: ['8.2']
                symfony-version: ['6.2']
        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v3

            - name: 'Install PHP with extensions'
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2
                  extensions: mbstring, intl, pdo, pdo_sqlite, sqlite3
                  ini-values: date.timezone=UTC

            - name: 'Install project dependencies'
              run: |
                  composer require --no-progress --no-scripts --no-plugins symfony/flex
                  composer config extra.symfony.require "${{ matrix.symfony-version }}"
                  composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable --ignore-platform-req=php
                  vendor/bin/simple-phpunit install

            - name: 'Run tests'
              run: vendor/bin/simple-phpunit -v || exit 0
