# OS: Linux; Symfony: upcoming (still unreleased) version; PHP: latest stable
name: "Tests - Upcoming Symfony version (5.4)"

on:
    pull_request:
    push:
        branches:
            - 'master'

env:
    fail-fast: true

jobs:
    tests:
        runs-on: 'ubuntu-latest'
        continue-on-error: true
        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v2.3.3

            - name: 'Install PHP with extensions'
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: '8.0'
                  tools: composer:v2
                  extensions: mbstring, intl, pdo, pdo_sqlite, sqlite3
                  ini-values: date.timezone=UTC

            - name: 'Install project dependencies'
              env:
                  SYMFONY_REQUIRE: '5.4.x@dev'
              run: |
                  composer global require --no-progress --no-scripts --no-plugins symfony/flex
                  composer config minimum-stability dev
                  composer update --no-interaction --prefer-dist --optimize-autoloader
                  vendor/bin/simple-phpunit install

            - name: 'Run tests'
              env:
                  SYMFONY_DEPRECATIONS_HELPER: 'max[indirect]=9999&max[direct]=0&max[self]=9999'
              run: vendor/bin/simple-phpunit -v || exit 0
